version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - event-platform
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    mem_limit: 1g

  payment_backend_service:
    build:
      context: ../payments
      dockerfile: Dockerfile.backend
    container_name: payment_backend
    ports:
      - "8001:8000"
    networks:
      - event-platform
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/payments_db"  #  DB service
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"
    depends_on:
      - rabbitmq
      - db

  payment_frontend_service:
    build:
      context: ../payments
      dockerfile: Dockerfile.frontend
    container_name: payment_frontend
    ports:
      - "3002:3000"
    networks:
      - event-platform
    working_dir: /app
    command: ["npm", "start"]
    depends_on:
      - payment_backend_service

  order_service:
    build:
      context: ../orders
      dockerfile: Dockerfile
    container_name: order_service
    ports:
      - "8002:8000"  # Expose the order service on port 8002
    networks:
      - event-platform
    environment:
      DATABASE_URL: "postgresql://user:password@order_db:5432/order_db"  # DB
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"
    depends_on:
      - rabbitmq
      - order_db

  db: #  PostgreSQL service for payments
    image: postgres:13
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - event-platform
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments_db

  order_db: # PostgreSQL service for orders
    image: postgres:13
    container_name: order_db
    volumes:
      - order_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - event-platform
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db

  catalog_backend:
    build:
      context: ../catalog
      dockerfile: Dockerfile.backend
    container_name: catalog_backend
    env_file:
      - ../catalog/backend/.env
    ports:
      - "8004:8000"
    networks:
      - event-platform
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"
    depends_on:
      - cat_mongo_db
      - rabbitmq
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  catalog_frontend:
    build:
      context: ../catalog
      dockerfile: Dockerfile.frontend
    container_name: catalog_frontend
    ports:
      - "3001:3000"
    networks:
      - event-platform
    working_dir: /app # Set the working directory to /app
    command: ["npm", "start"]
    depends_on:
      - catalog_backend

  cat_mongo_db:
    image: mongo:latest
    container_name: cat_mongo_db
    env_file:
      - ./.env.catalog
    volumes:
      - mongo_cat:/data/db
    ports:
      - '6001:27017'
    networks:
      - event-platform

  auth_backend:
    image: palani1703/auth-backend:latest
    container_name: auth_backend
    env_file:
      - ../jwt-auth/.env
    ports:
      - "8005:8000"
    networks:
      - event-platform
    depends_on:
      - auth_mongo_db
    volumes:
      - ../jwt-auth:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  auth_frontend:
    image: palani1703/auth-frontend:latest
    container_name: auth_frontend
    ports:
      - "3003:3000"
    networks:
      - event-platform
    working_dir: /app
    command: ["npm", "start"]
    depends_on:
      - auth_backend

  auth_mongo_db:
    image: mongo:latest
    container_name: auth_mongo_db
    env_file:
      - ./.env.auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE_AUTH}
    volumes:
      - mongo_auth:/data/db
    ports:
      - '6000:27017'
    networks:
      - event-platform
  
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"  # Expose NGINX on port 80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the custom NGINX configuration
  #   networks:
  #     - event-platform
  #   depends_on:
  #     - payment_frontend_service
  #     - order_service
  #     - catalog_frontend
  #     - auth_frontend


networks:
  event-platform:
    driver: bridge

volumes:
  db_data:
  order_db_data:
  mongo_auth:
  mongo_cat:
